### ISSUE TITLE
Accuracy of likelihood doesn't increase with the number of bins

### ISSUE THREAD

**Issue by krishnakruthi** [adivijaykumar/bilby#15]
When we change the number of bins by changing `epsilon`, the accuracy doesn't seem to improve. 
To do:
- [x] Make `setup_bins` more readable. (@adivijaykumar #16)
- [x] Crosscheck the likelihood comparison plots for the bilby case. (@adivijaykumar)
- [x] Compare the `setup_bins` function in bilby to the one in IAS code. (@Kruthi24) 
- [x] Incorporate masking in `get_detector_response`. (@Kruthi24) 
- [x] Check if `inteferometer.frequency_array` and `waveform_generator.frequency_array` are consistent. (@Kruthi24)  
- [x] Check  for errors in`lal_binary_black_hole_relativebinning` and `lal_binary_neutron_star_relativebinning`. (@Kruthi24)

**Comment by krishnakruthi** [comment]
The frequencies at the bin edges obtained using `setup_bins` in bilby and IAS seem to match. In fact, the bilby one is better because the implementation in IAS code seems to produce duplicate values for 1 or 2 bin edges.

**Comment by krishnakruthi** [comment]
`inteferometer.frequency_array` and `waveform_generator.frequency_array` match!

**Comment by adivijaykumar** [comment]
Closed with #19
