### ISSUE TITLE
 Is the likelihood calculation correct?

### ISSUE THREAD

**Issue by adivijaykumar** [adivijaykumar/bilby#6]
I did a naive test run, and it seems that the distance estimates are a bit off. This could be due to the summary data calculation here

https://github.com/adivijaykumar/bilby/blob/9ab7608f537a4634f74a44ee9165662ecffea48b/bilby/gw/likelihood.py#L1617

 have done some weird gymnastics there. @Kruthi24 could you check if this is consistent? What you need to check is if we really need the division by 2 in each of `a0, a1, b0, b1`.

**Comment by adivijaykumar** [comment]
https://github.com/adivijaykumar/bilby/blob/9ab7608f537a4634f74a44ee9165662ecffea48b/bilby/gw/likelihood.py#L1617

**Comment by krishnakruthi** [comment]
According to the formulae we have, I don't think we need the division by 2.

**Comment by adivijaykumar** [comment]
Could you remove that also then?

**Comment by adivijaykumar** [comment]
You would also have to check the exact likelihood calculation within bilby
also to make sure the 2 factor is not needed

**Comment by krishnakruthi** [comment]
Yup, I checked how the `noise_weighted_inner_product` function is defined. Shall I go ahead and remove 2?
Also, is there any reason for it to be there in the first place?

**Comment by adivijaykumar** [comment]
No, I think it most probably slipped in by mistake. Please make this change!

Also, please create a different pull request for this and include the "removing `log_likelihood_ratio_approx`" change and the commenting out change that I made to `conversion.py` --- that way we can merge this in right now and start runs.
