### ISSUE TITLE
Error with conversion function

### ISSUE THREAD

**Issue by krishnakruthi** [adivijaykumar/bilby#7]
We are getting the following error (screenshots attached) when we use `conversion_function= bilby.gw.conversion.generate_all_bns_parameters` in `bilby. run_sampler`. This is due to the fact that in `conversion.py`, `likelihood.calculate_snrs` is being called instead of `likelihood.calculate_snrs_from_summary_data`. A temporary fix for this issue has been made here #5 

![Screen Shot 2020-11-04 at 10 05 00 PM](https://user-images.githubusercontent.com/48632511/98485914-fbef9a80-223f-11eb-8674-0e707886de71.png)
![Screen Shot 2020-11-04 at 10 04 45 PM (1)](https://user-images.githubusercontent.com/48632511/98485918-014ce500-2240-11eb-97e2-8d98ae13f4c1.png)

**Comment by adivijaykumar** [comment]
@Kruthi24 I think I have found a way to solve this problem --- basically one has to change the `compute_snrs` function inside `conversion.py` by adding a case with the following statement:

`if isinstance(likelihood, RelativeBinningGravitationalWaveTransient):`

Of course one will have to add more changes to the function, but this can be done.
